apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-room-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-room-booking
  template:
    metadata:
      labels:
        app: meeting-room-booking
    spec:
      containers:
        - name: app
          image: meeting-room-booking:latest
          imagePullPolicy: Never